url: "https://Ray2024Ray.github.io"
baseurl: "/cross-cultural-stories-website"

podcast:
  name: " Cross-cultural Stories | 他乡与故乡"
  tagline: "跨文化的相遇与共鸣｜Stories of identity, belonging, and becoming"
  cover: "/images/podcast-cover.png"   
  spotify_show: "https://open.spotify.com/show/6SNCpFk0GlnuIaLw8D3QGA"
  apple_show: "https://podcasts.apple.com/us/podcast/cross-cultural-stories/id1831182815"        
  xiaoyuzhou_show: "https://www.xiaoyuzhoufm.com/podcast/686cb2e71408ff0abb1ee127"   
  costbox_show: "https://castbox.fm/vh/6702883"      

plugins:
  - jekyll-bookshop
  - jekyll-sitemap
  - jekyll/tagging
  - jekyll-polyglot

languages: ["en", "zh", "ko"]   # 开启的语言
default_lang: "zh"              # 你想默认展示中文就用 zh

# 不需要按语言复制的静态资源
exclude_from_localization:
  - assets
  - images
  - favicon.ico
  - admin
  - CNAME

# 如果你用 collections 存节目
localized_collections:
  - episodes

# Multiple bookshops can be used on one website,
# or different production / staging locations.
bookshop_locations:
  - ../component-library

exclude:
  - postcss.config.js
  - node_modules

include:
  - _cloudcannon

collections_dir: 'collections'

collections:
  episodes:
    output: true
    permalink: /episodes/:name/
  projects:
    output: true
    permalink: /project/:slug
  testimonials:
    output: false
  posts:
    output: true
    permalink: /blog/:slug

defaults:
  - scope:
      path: ""
    values:
      layout: default
  - scope:
      type: pages
      path: _pages/index.html
    values:
      permalink: /
  - scope:
      type: projects
    values:
      layout: project
  - scope:
      type: posts
    values:
      layout: post

# Tags
tag_page_dir: tag
tag_page_layout: tag_page
tag_permalink_style: /:title

podcast:
  name: "Cross-cultural Stories | 他乡与故乡"
  tagline: "跨文化的相遇与共鸣｜You may hear your own story in ours"
  spotify_show: "https://open.spotify.com/show/6SNCpFk0GlnuIaLw8D3QGA"
  apple_show: "https://podcasts.apple.com/us/podcast/cross-cultural-stories/id1831182815"
  xiaoyuzhou_show: "https://www.xiaoyuzhoufm.com/podcast/686cb2e71408ff0abb1ee127"
  castbox_show: "https://castbox.fm/channel/id6702883?country=us"

